"""
Neamt Scribe — main.py

Callable actions exposed to the neamt bridge:
  process_video(url, output_dir=None)
  list_notes()
  get_note(filename)
  delete_note(filename)

_neamt_guard is injected into this module's globals by the sandbox at runtime.
All imports must avoid: os, sys, subprocess, shutil, socket, asyncio, threading,
importlib, requests, httpx, urllib, urllib3, builtins, ctypes.
"""

from __future__ import annotations

import json
import pathlib
import re
from datetime import datetime

# Injected by the Neamt sandbox — do not assign here, just declare for type checkers
_neamt_guard = None  # type: ignore[assignment]

_NOTES_DIR = pathlib.Path.home() / ".neamt" / "data" / "scribe" / "notes"
_TMP_DIR   = pathlib.Path.home() / ".neamt" / "data" / "scribe" / ".tmp"

_MAX_TRANSCRIPT_CHARS = 180_000

_SYSTEM_PROMPT = """\
You are an expert analyst that converts YouTube video transcripts into comprehensive, \
structured Markdown notes for future reference.

Your notes must be dense with information — not superficial summaries. \
Capture every key concept, data point, argument, and insight from the transcript.\
"""

_NOTE_TEMPLATE = """\
Convert the following YouTube video transcript into structured Markdown notes.

VIDEO METADATA
--------------
Title    : {title}
URL      : {url}
Duration : {duration}
Date     : {date}

TRANSCRIPT
----------
{transcript}

---

Generate the notes using this exact structure:

# {title}

> **Source:** {url}
> **Date:** {date}

## Executive Summary
(2–3 sentences capturing the core thesis or purpose of the video)

## Key Concepts
- **Concept name**: clear explanation

## Main Points
### Point 1 — descriptive heading
Detailed explanation preserving numbers, names, and reasoning.

### Point 2 — ...

## Important Quotes
> "Direct quote from the transcript"
> — context of who said it / when

## Data & Statistics
| Metric | Value | Context |
|--------|-------|---------|
| ...    | ...   | ...     |

## Action Items / Takeaways
- [ ] Concrete takeaway or action

---
*Generated by Neamt Scribe*
"""


def _get_api_key() -> str:
    from neamt.config import get_config  # neamt is not in the blocked list
    key = get_config("anthropic_api_key")
    if not key:
        raise RuntimeError(
            "Anthropic API key not configured. "
            "Run: neamt config set anthropic_api_key <your-key>"
        )
    return key


def _slugify(text: str, max_len: int = 60) -> str:
    slug = re.sub(r"[^\w\s-]", "", text.lower())
    slug = re.sub(r"[\s_-]+", "-", slug).strip("-")
    return slug[:max_len]


def _format_duration(seconds: int) -> str:
    if not seconds:
        return "unknown"
    h, rem = divmod(seconds, 3600)
    m, s = divmod(rem, 60)
    return f"{h}h {m}m" if h else f"{m}m {s}s"


def _truncate_transcript(transcript: str) -> str:
    if len(transcript) <= _MAX_TRANSCRIPT_CHARS:
        return transcript
    half = _MAX_TRANSCRIPT_CHARS // 2
    return (
        transcript[:half]
        + "\n\n[... middle section omitted for length ...]\n\n"
        + transcript[-half:]
    )


# ── Public actions ──────────────────────────────────────────────────────────


def process_video(url: str, output_dir: str = None) -> dict:
    """Download, transcribe, and generate Markdown notes for a YouTube video."""
    _neamt_guard.require("internet")
    _neamt_guard.require("anthropic_api")
    _neamt_guard.require("filesystem:write")

    import yt_dlp
    import whisper
    import anthropic

    # ── 1. Prepare directories ──────────────────────────────────────────────
    _TMP_DIR.mkdir(parents=True, exist_ok=True)
    notes_dir = pathlib.Path(output_dir) if output_dir else _NOTES_DIR
    notes_dir.mkdir(parents=True, exist_ok=True)

    # ── 2. Download audio ───────────────────────────────────────────────────
    downloaded_path: pathlib.Path | None = None
    video_title = "Unknown"
    video_id = "unknown"
    video_duration = 0
    video_date = datetime.now().strftime("%Y-%m-%d")

    class _Logger:
        def debug(self, msg: str) -> None: pass
        def info(self, msg: str) -> None: pass
        def warning(self, msg: str) -> None: pass
        def error(self, msg: str) -> None: pass

    class _Hook:
        info_dict: dict = {}
        def __call__(self, d: dict) -> None:
            if d.get("status") == "finished" and d.get("info_dict"):
                self.info_dict = d["info_dict"]

    hook = _Hook()

    # Try with ffmpeg (mp3); if ffmpeg is absent yt-dlp will raise and we retry
    # without the postprocessor, keeping the native format.
    def _ydl_opts(use_ffmpeg: bool) -> dict:
        opts: dict = {
            "format": "bestaudio/best",
            "outtmpl": str(_TMP_DIR / "%(id)s.%(ext)s"),
            "quiet": True,
            "no_warnings": True,
            "progress_hooks": [hook],
            "logger": _Logger(),
        }
        if use_ffmpeg:
            opts["postprocessors"] = [{
                "key": "FFmpegExtractAudio",
                "preferredcodec": "mp3",
                "preferredquality": "64",
            }]
        return opts

    for attempt, use_ffmpeg in enumerate([True, False]):
        try:
            with yt_dlp.YoutubeDL(_ydl_opts(use_ffmpeg)) as ydl:
                info = ydl.extract_info(url, download=True)

            video_title    = info.get("title", "Unknown")
            video_id       = info.get("id", "unknown")
            video_duration = info.get("duration") or 0
            ud = info.get("upload_date", "")
            if ud and len(ud) == 8:
                video_date = f"{ud[:4]}-{ud[4:6]}-{ud[6:8]}"

            # Locate the downloaded file
            if hook.info_dict.get("filepath"):
                downloaded_path = pathlib.Path(hook.info_dict["filepath"])
            if not downloaded_path or not downloaded_path.exists():
                candidates = sorted(_TMP_DIR.glob(f"{video_id}.*"))
                downloaded_path = candidates[0] if candidates else None

            if downloaded_path and downloaded_path.exists():
                break
        except Exception as exc:
            if attempt == 1:
                raise RuntimeError(f"Audio download failed: {exc}") from exc

    if not downloaded_path or not downloaded_path.exists():
        raise RuntimeError(f"No audio file found after download for: {url}")

    # ── 3. Transcribe ───────────────────────────────────────────────────────
    try:
        model = whisper.load_model("base")
        result = model.transcribe(
            str(downloaded_path),
            task="transcribe",
            verbose=False,
            fp16=False,
            condition_on_previous_text=True,
        )
        transcript: str = result.get("text", "").strip()
    finally:
        if downloaded_path.exists():
            downloaded_path.unlink()

    if not transcript:
        raise RuntimeError("Whisper returned an empty transcript")

    # ── 4. Generate notes with Claude ───────────────────────────────────────
    api_key = _get_api_key()
    client = anthropic.Anthropic(api_key=api_key)

    prompt = _NOTE_TEMPLATE.format(
        title=video_title,
        url=url,
        duration=_format_duration(video_duration),
        date=video_date,
        transcript=_truncate_transcript(transcript),
    )

    message = client.messages.create(
        model="claude-haiku-4-5-20251001",
        max_tokens=4096,
        system=_SYSTEM_PROMPT,
        messages=[{"role": "user", "content": prompt}],
    )
    notes_md: str = message.content[0].text

    # ── 5. Save note ────────────────────────────────────────────────────────
    slug = _slugify(video_title)
    filename = f"{video_date}_{slug}.md"
    note_path = notes_dir / filename
    note_path.write_text(notes_md, encoding="utf-8")

    return {
        "status": "done",
        "title": video_title,
        "path": str(note_path),
        "filename": filename,
        "word_count": len(notes_md.split()),
    }


def list_notes() -> dict:
    """Return metadata for all saved notes."""
    notes: list[dict] = []

    if not _NOTES_DIR.exists():
        return {"notes": notes}

    for p in sorted(_NOTES_DIR.iterdir(), key=lambda x: x.stat().st_mtime, reverse=True):
        if p.suffix != ".md":
            continue
        content = p.read_text(encoding="utf-8")
        first_line = content.splitlines()[0] if content else ""
        title = re.sub(r"^#+\s*", "", first_line).strip() or p.stem
        created_at = datetime.fromtimestamp(p.stat().st_mtime).strftime("%Y-%m-%d %H:%M")
        size_kb = round(p.stat().st_size / 1024, 1)
        notes.append({
            "filename": p.name,
            "title": title,
            "created_at": created_at,
            "size_kb": size_kb,
        })

    return {"notes": notes}


def get_note(filename: str) -> dict:
    """Read a single note by filename."""
    safe_name = pathlib.Path(filename).name  # strip any path components
    path = _NOTES_DIR / safe_name
    if not path.exists():
        raise FileNotFoundError(f"Note not found: {safe_name}")
    return {"content": path.read_text(encoding="utf-8"), "filename": safe_name}


def delete_note(filename: str) -> dict:
    """Delete a note by filename."""
    _neamt_guard.require("filesystem:write")
    safe_name = pathlib.Path(filename).name
    path = _NOTES_DIR / safe_name
    if not path.exists():
        raise FileNotFoundError(f"Note not found: {safe_name}")
    path.unlink()
    return {"status": "deleted", "filename": safe_name}
